vim.opt.clipboard = { 'unnamed', 'unnamedplus' }
vim.opt.autoindent = true
vim.opt.cursorline = true
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = 'expr'
vim.opt.ignorecase = true -- ignore search case
vim.opt.inccommand = 'split'
vim.opt.list = true
vim.opt.modeline = false
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.showmode = false
vim.opt.signcolumn = 'yes'
vim.opt.smartcase = true -- enable casing if uppercase
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 250
vim.opt.wrap = true
