SERVER=
CONTAINER_REGISTRY=
CONTAINER_REGISTRY_USER=
TAG=
BUILD_PATH=

.PHONY: help format lint dev build publish

## help: print this help message
help:
	@echo 'Usage:'
	@echo ${MAKEFILE_LIST}
	@sed -n 's/^##//p' ${MAKEFILE_LIST} | column -t -s ':' |  sed -e 's/^/ /'

## format: format files
format:
	@echo not implemented && exit 1

## format: format files
lint:
	@echo not implemented && exit 1

## dev: starts dev server
dev:
	@echo not implemented && exit 1

## build: build container
build:
	@echo not implemented && exit 1

## publish: publish docker container
publish:
	@echo not implemented && exit 1

## deploy: deploy service
deploy: 
	@echo not implemented && exit 1
