#!/usr/bin/env bash

# INFO: powerline10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# INFO: alias
alias "?"="ai chat -p"
alias ai="node ~/wte/ai/main.ts"
alias aic="ai commit"
alias aiplan="ai chat -i ~/wte/ai/plan.md -p"
alias alert="espeak 'weewoo weewoo weewoo'"
alias cla="ai -m anthropic/claude-opus-4.1"
alias ga="git add"
alias gc="ai commit"
alias gca="git commit --amend --verbose"
alias gem="ai -m google/gemini-2.5-pro"
alias gl="git pull"
alias glo="git log"
alias gp="git push"
alias gpt="ai -m openai/gpt-5.1"
alias gptc="ai -m openai/gpt-5-codex"
alias grok="ai -m x-ai/grok-4-fast"
alias k2="ai -m moonshotai/kimi-k2"
alias lg="lazygit"
alias micu="echo '5-1' | sudo tee /sys/bus/usb/drivers/usb/unbind"
alias micd="echo '5-1' | sudo tee /sys/bus/usb/drivers/usb/bind"
alias mm="ai -m minimax/minimax-m2"
alias n="cd ~/wte/notes && nvim ~/wte/notes/todo.md"
alias next="ai -m qwen/qwen3-next-80b-a3b-instruct"
alias oss="ai -m openai/gpt-oss-120b"
alias qwnc="ai -m qwen/qwen3-coder"
alias rss="node ~/wte/rss/main.ts"
alias tdel="tracker delete"
alias tinfo="tracker info"
alias tls="tracker list"
alias tracker="node ~/wte/tracker/main.ts"
alias tset="tracker set"
alias v="~/wte/dotfiles/scripts/nvim-picker.sh"
alias ytls='fd --full-path ~/wte/youtube -E "*.txt" | tail -n 30'
alias ytr="retry yt-dlp"
alias ytsync='cat ~/wte/youtube/channels.txt | xargs yt-dlp --match-filter "duration > 180" --playlist-end 10 -o "/home/jon/wte/youtube/%(upload_date>%Y-%m-%d)s [%(uploader)s] %(title)s.%(ext)s"'
alias ytwatch='ytls | mpv --playlist=-'

# INFO: functions
retry() {
    while ! $($@); do
        echo "Command $@ failed, retrying in 60 seconds..."
        sleep 60
    done
}

# INFO: path
[ -d "$HOME/.nvm" ] && export NVM_DIR=$HOME/.nvm
export BUN_INSTALL="$HOME/.bun"
export DOTNET_CLI_TELEMETRY_OPTOUT='true'
export CHROME_BIN='/usr/bin/chromium'
export EDITOR=nvim
export HUSKY=0
export MANPAGER='nvim +Man!'
export NODE_OPTIONS="--experimental-strip-types"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH=$PATH:$HOME/.dotnet/tools
export PATH=$PATH:$HOME/wte/dotfiles/scripts
export PATH=$PATH:/home/jon/.local/bin
export ZSH="$HOME/.oh-my-zsh"
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
[ ! -d "$ZSH_CACHE_DIR" ] && mkdir $ZSH_CACHE_DIR
ZSH_THEME=""

# INFO: source
[ -d "$HOME/.oh-my-zsh" ] && source $HOME/.oh-my-zsh/oh-my-zsh.sh
[ -d "$HOME/.zsh/powerlevel10k" ] && source $HOME/.zsh/powerlevel10k/powerlevel10k.zsh-theme
[ -d "$HOME/.zsh/zsh-autosuggestions" ] && source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -d "$HOME/.zsh/zsh-history-substring-search" ] && source $HOME/.zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
[ -d "$HOME/.zsh/zsh-syntax-highlighting" ] && source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -d "/usr/share/nvm" ] && source /usr/share/nvm/init-nvm.sh && source /usr/share/nvm/bash_completion
[ -s "$NVM_DIR/bash_completion" ] && source $NVM_DIR/bash_completion
[ -s "$NVM_DIR/nvm.sh" ] && source $NVM_DIR/nvm.sh
[ -s "$HOME/.bun/_bun" ] && source $HOME/.bun/_bun
[ -s "$HOME/.fzf.zsh" ] && source $HOME/.fzf.zsh
[ -s "$HOME/.p10k.zsh" ] && source $HOME/.p10k.zsh
[ -s "$HOME/.secrets" ] && source $HOME/.secrets
